Restructure flask app for pytest
Previous setup caused the following error *only when running pytest*:
```
AssertionError: View function mapping is overwriting an existing endpoint function
```
This structure runs with pytest and is still compatible with pyproject.toml
script entry point.